export const MAX_CHALLENGES = 5;
export const QUESTIONS_PER_DAY = 3;
export const ALERT_TIME_MS = 2000;
export const LONG_ALERT_TIME_MS = 10000;
export const REVEAL_TIME_MS = 350;
export const MANUAL_OFFSET = 0; // Used to calibrate questions to days mapping
// export const WELCOME_INFO_MODAL_MS = 350;
// export const DISCOURAGE_INAPP_BROWSERS = true;
// export const ENABLE_ARCHIVED_GAMES = false;
