export const MAX_CHALLENGES = 5;
export const QUESTIONS_PER_DAY = 1;
export const ALERT_TIME_MS = 2000;
export const LONG_ALERT_TIME_MS = 10000;
export const REVEAL_TIME_MS = 100;
export const PULSE_TYPE_MS = 150;
export const THEME_TRANSITION_TIME_MS = 100;
export const MANUAL_OFFSET = -5; // Used to calibrate questions to days mapping
export const MOBILE_SCREEN_CUTOFF = "600px";
export const MAX_CATEGORY_STRING_LENGTH = 3;
// export const WELCOME_INFO_MODAL_MS = 350;
// export const DISCOURAGE_INAPP_BROWSERS = true;
// export const ENABLE_ARCHIVED_GAMES = false;
